### ISSUE TITLE
As a new user, I'd like to be able to create an account on the system so that I can enter the necessary information to gain access to the inventory control and sales forecasting features.

### ISSUE THREAD

**Issue by sairam-kakarla** [sairam-kakarla/CSCE_5430_Group_2#1]
# Estimated time:
Small

# Acceptance criteria:
Users should be able to enter their details such as email, name, DOB, etc., and register and log in to the website.

# Backlog

# Tasks
- [x] To create the login page
- [x] To link the page with db
- [x] To create a signup page
- [x] To link the signup page with db

**Comment by Hasa3891** [comment]
As a new user, I want to use GitHub to learn about version control and collaborative coding practises, which will help me become a more proficient developer.
