### ISSUE TITLE
As a user, I want to view a complete and coordinated overview of all inventory items available, including their quantities, classifications, and other relevant details.

### ISSUE THREAD

**Issue by asowmyasri** [sairam-kakarla/CSCE_5430_Group_2#2]
# Estimated time:
Large

# Acceptance Criteria:
User will have access to a unified inventory page that clearly and efficiently lists all of the items that are currently accessible along with their corresponding quantities, classifications, and other details of products.

# BackLog

# Tasks         
- [x] Create a dashboard page.
- [x] Integrate the page with the navbar.
- [x] Business Logic of dashboard charts.
- [x] Add charts to the dashboard.

**Comment by asowmyasri** [comment]
#Estimated time:
Large

#Acceptance Criteria:
User will have access to a unified inventory page that clearly and efficiently lists all of the items that are currently accessible along with their corresponding quantities, classifications, and other details of products.
