### ISSUE TITLE
As a  user, I want to make sure that the Inventory is up to date., so that I can add new products that are in huge demand and remove the items that are stocked over a period of time with very less sales. 

### ISSUE THREAD

**Issue by Chandrikak08** [sairam-kakarla/CSCE_5430_Group_2#3]
# Estimated time:
Large

# Acceptance criteria:
Users must be able to add, delete, and modify items present in the inventory.

#  Backlog

# Tasks
- [x] Page to add inventory.
- [x] Integrate delete and modify buttons.
- [x] Business Logic and Db integration
- [x] Page to list inventory
