### ISSUE TITLE
As a user, I want to utilize the platform to study historical data and trend analysis so that I may identify trends and make informed decisions based on past performance.

### ISSUE THREAD

**Issue by Hasa3891** [sairam-kakarla/CSCE_5430_Group_2#4]
# Estimated time:
Large

# Acceptance criteria:
The dashboard must show the daily sales graph and prediction lines indicating the direction of sales and generate estimates for the coming days.

# Backlog

# Tasks
- [x] Implement the ML Model for sales prediction.
- [x] Integrated the ML model into the dashboard.
- [x] Update the dashboard front page.
- [x] Update the dashboard business logic.

**Comment by akshaykumarkona** [comment]
I am willing to contribute to this project. You can check my GitHub portfolio for your reference.

**Comment by Hasa3891** [comment]
#Estimated time:
Large

#Acceptance criteria:
to enter the small-scale owner's sales history into the database for data analysis in order to get a more accurate sales analysis output

**Comment by akshaykumarkona** [comment]
I did not get your views clearly.
