### ISSUE TITLE
As a user, I want to get sales forecasts for each inventory item based on machine learning model that has been developed, since this would improve inventory control and business decision making.

### ISSUE THREAD

**Issue by Anjanim9** [sairam-kakarla/CSCE_5430_Group_2#5]
# Estimated time:
Large

# Acceptence Criteria:
Small-scale business owners can able to predict future sales, demands, and trends based on previous data, market analysis and forecasting methods.

# Backlogs

# Tasks
- [x] To create a prediction page.
- [x] Integrate the prediction page into the navbar.
- [x] Implement prediction business logic.
