### ISSUE TITLE
As a user, I want to transfer inventory between store locations efficiently,  So that I can balance stock levels and meet customer demand across different locations.

### ISSUE THREAD

**Issue by Meghana1914** [sairam-kakarla/CSCE_5430_Group_2#6]
# Estimated Time:
Large

# Acceptance Criteria :
The user shall export the data in CSV format successfully and It tracks and updates stock levels in real-time for both sending and receiving locations.

# Backlog

# Tasks
- [x] Create an export data page.
- [x] Implement export csv business logic. 
- [x] Linking the logic to Db.
