### ISSUE TITLE
As a user, I want to make sure that the alert mechanism is there so that I can stay updated with the inventory stock value and help in restocking products.

### ISSUE THREAD

**Issue by Chandrikak08** [sairam-kakarla/CSCE_5430_Group_2#7]
# Estimated time:
Large

# Acceptance criteria:
The user is receiving Email Notifications whenever the quantity of stock of a certain product follows below a pre-defined threshold.

# Backlog

# Tasks
- [x] Implement the email logic.
- [x] Integration with Db.
- [x] Integration with app.py
- [x] Create Email Templates.
