### ISSUE TITLE
As a user, I want to receive recommendations for optimal reorder quantities based on sales predictions and current inventory levels, so that I can streamline the restocking process and minimize excess inventory.

### ISSUE THREAD

**Issue by Nithin027** [sairam-kakarla/CSCE_5430_Group_2#9]
# Estimated time:
Large

# Acceptance criteria:
Users should be able to enter their stock inventory details and purchase power quantity.

# Backlog

# Tasks
- [x] Business Logic and Db integration
- [x] Updated dashboard to integrate predictions.
- [x] Integration with Db.
